version: "3.8"
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres/data

  app:
    depends_on:
      - db
    build: .
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 7001:7001
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
    driver: local