spring:
  application:
    name: user-service
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password

server:
  port: 7001